name: go_responsive
description: >
  A simple but expressive responsive framework inspired by
  responsive_framework & responsive_builder with code generation support.
version: 0.5.0
homepage: https://pub.dev/packages/go_responsive
repository: https://github.com/burhankhanzada/go_responsive
issue_tracker: https://github.com/burhankhanzada/go_responsive/issues

resolution: workspace

environment:
  sdk: ^3.8.0
  
dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1

dev_dependencies:
  flutter_lints: ^6.0.0
