name: workspace

publish_to: none

environment:
  sdk: ^3.8.0

workspace:
  - packages/go_responsive
  - packages/go_responsive_annotation
  - packages/go_responsive_generator
  - examples/simple
  - examples/navigation

dev_dependencies:
  melos: ^7.3.0

melos: 
  name: workspace

  ide:
    intellij:
      enabled: false

  packages:
    - examples/*
    - packages/*